In [4]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional
import numpy as np
import pandas as pd

In [6]:
# 读取原始文件,写入到一张表中

gearbox_initial = []
for i in range(5):
    gearbox_initial.append(pd.read_excel('原始数据.xlsx', i, dtype=np.float32).iloc[:,:5])
    gearbox_initial[i]['target'] = i

temp = pd.concat(gearbox_initial)
temp.to_excel('原始数据一张表.xlsx')

In [25]:
# 读取训练文件

data = pd.read_excel('原始数据一张表.xlsx')


In [29]:
# 创建模型初始

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(1, 4)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 50)                11000     
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 11,051
Trainable params: 11,051
Non-trainable params: 0
_________________________________________________________________
None


In [30]:

X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:4], data.iloc[:,-1], train_size=0.75, random_state=0)
X_train = np.array(X_train).reshape(len(X_train),1,4)
print(X_train)

[[[ 6.70200000e+03  1.25313001e-02 -4.18750010e-03  3.46875004e-02]]

 [[ 1.68800000e+03  1.58594009e-02  6.31250022e-03  2.00155992e-02]]

 [[ 2.88920000e+04  1.10938004e-03  3.37500013e-02  7.43750017e-03]]

 ...

 [[ 7.73900000e+03  1.89219005e-02 -1.82812999e-03  7.70469010e-02]]

 [[ 3.52000000e+02  1.60000008e-02  2.38438006e-02 -6.06250018e-03]]

 [[ 1.41670000e+04 -7.47656003e-02  7.98438024e-03 -3.83593999e-02]]]


In [31]:
model.fit(X_train, y_train, epochs=8, validation_split=0.2, batch_size=5)


Epoch 1/8
17640/17640 [==============================] - 16s 856us/step - loss: 433.3264 - val_loss: 2.3213
Epoch 2/8
17640/17640 [==============================] - 14s 819us/step - loss: 27.6121 - val_loss: 2.7191
Epoch 3/8
17640/17640 [==============================] - 16s 897us/step - loss: 5.9027 - val_loss: 2.3446
Epoch 4/8
17640/17640 [==============================] - 16s 933us/step - loss: 4.8898 - val_loss: 5.4037
Epoch 5/8
17640/17640 [==============================] - 16s 906us/step - loss: 3.9638 - val_loss: 2.3327
Epoch 6/8
17640/17640 [==============================] - 17s 968us/step - loss: 3.1067 - val_loss: 2.0174
Epoch 7/8
17640/17640 [==============================] - 15s 846us/step - loss: 2.0568 - val_loss: 1.9978
Epoch 8/8
17640/17640 [==============================] - 19s 1ms/step - loss: 1.9999 - val_loss: 1.9975


In [32]:
X_test = np.array(X_test).reshape(len(X_test),1,4)
print(model.predict(X_test))

[[2.0030081]
 [2.0030081]
 [2.0030081]
 ...
 [2.0030081]
 [2.0030081]
 [2.0030081]]
